### ISSUE TITLE
Fatal error: exception Reason_syntax_util.Error

### ISSUE THREAD

**Issue by alexfedoseev** [cknitt/bs-react-intl-extractor#18]
Hey, I'm trying to run extractor on a new code and it fails w/ error:

```
Fatal error: exception Reason_syntax_util.Error(_, _)
```

I checked it on the old project and it works. I assume it's b/c of some new syntax but not sure.

**Comment by cknitt** [comment]
Yes, that's because I have not released a new version with the latest (3.3.3) Reason parser yet. I will do that over the weekend.

**Comment by alexfedoseev** [comment]
Awesome, thanks!

**Comment by cknitt** [comment]
Fixed in version 0.5.0.
