### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by baransu** [cknitt/bs-react-intl-extractor#33]
Current NPM version throws on `bs-platform@4.0.18` codebase because of `reason@3.4.0`. I see that latest version is updated to `reason@3.4.0` but no published to NPM.
Here is error.
```
Fatal error: exception Reason_syntax_util.Error(_, _)
```
It's gone with latest version. It would be great to have that on NPM.

**Comment by cknitt** [comment]
Hi @baransu! I am currently on vacation and will publish to NPM as soon as I am back (Monday). Thanks for your patience!

**Comment by baransu** [comment]
No problem! Thanks for the quick response. For now I'm using local version but would be great to have that automated back again 🙂

**Comment by cknitt** [comment]
Sorry, did not make it yesterday. But now 0.7.0 is out! 🎉
