### ISSUE TITLE
Compatibility with bs-react-intl@1.0.0?

### ISSUE THREAD

**Issue by dfalling** [cknitt/bs-react-intl-extractor#38]
Should this extractor work with the latest bs-react-intl?  I upgraded my app using a number of the ReactIntlCompat packages, and when I run this tool it generates an empty array rather than all the translations.

**Comment by cknitt** [comment]
The extractor works on the parse tree and therefore does not directly depend on the `bs-react-intl` version. The patterns it can currently detect are described in https://github.com/cknitt/bs-react-intl-extractor/blob/master/README.md.

So e.g.

```reason
<ReactIntl.FormattedMessage id="some.message.id" defaultMessage="Some message" />
```

and

```reason
<FormattedMessage id="some.message.id" defaultMessage="Some message" />
```

will work, but

```reason
<ReactIntlCompat.FormattedMessage id="some.message.id" defaultMessage="Some message" />
```

won't.

Do you have an example source file where the messages cannot be extracted?

**Comment by cknitt** [comment]
Ok, can you please show me the part of the code where you define the strings in the separate module?

**Comment by cknitt** [comment]
Ok, the problem here is that the `[@intl.messages]` annotation is in the wrong place. It should be

```reason
let appLocale =
  [@intl.messages]
  {
    "cancel": {
      "id": "app.cancel",
      "defaultMessage": "Cancel",
    },
    "fourOhFour": {
      "id": "app.fourOhFour",
      "defaultMessage": "404",
    },
  };
```
