### ISSUE TITLE
Support breaking syntax changes in bs-platform 7.1.0 / reason latest

### ISSUE THREAD

**Issue by jchavarri** [cknitt/bs-react-intl-extractor#41]
In most recent version 7.1.0, BuckleScript also updated to the latest version of Reason parser, which included a change to the way `bs.obj` externals are declared, making the empty string optional: https://github.com/facebook/reason/pull/2464.

To add to that, refmt now picks the option of removing the empty string by default with no way to configure that. So when we ran bsrefmt through our codebase, all empty strings from `bs.obj` externals were removed.

This situation breaks `bs-react-intl-extractor` because `bs.obj` without strings was legitimately not valid syntax in Reason 3.5.2, the version of the parser that `bs-react-intl-extractor` is currently using.

Probable fix involves just updating dep to latest:
https://github.com/cknitt/bs-react-intl-extractor/blob/3aa00958695881ac9ea116a5fddd4fd2b457f27e/package.json#L26

But unfortunately there's been no new release for `@esy-ocaml/reason` [in npm](https://www.npmjs.com/package/@esy-ocaml/reason), so I guess a `resolution` can be used for esy to pick the right version?

**Comment by cknitt** [comment]
@jchavarri Yes, that's why I have not created a new release yet after the last commit (version bumps by @alexfedoseev) - I was waiting for `@esy-ocaml/reason@3.6.0`, too.

The 3.6.0 release might be coming soon though, at least it is already in https://github.com/facebook/reason/blob/master/HISTORY.md. Maybe @ryyppy knows more?

If not than I am happy with using a `resolution` in the meantime - would you like to create a PR for that? Otherwise I can look into it over the coming weekend.

**Comment by jchavarri** [comment]
Sounds good! Added a PR in #42, please lmk if anything's missing :)

Side note: if you are planning to move the repo to GH actions, please take a look at https://github.com/jchavarri/hello-ppx-esy. It includes GH workflow that:
- supports creating artifacts for all 3 platforms (win, mac, linux)
- uses GH cache for faster builds
- defines rules for publishing to npm directly, when commits in `master` are tagged with `v*`.

I think the distribution of ppx used over there could be helpful for this tool as well, and also, if you have any ideas on how the setup, scripts, etc could be simplified, I'll be more than happy to incorporate them back into the hello-ppx-esy project. Thanks!

**Comment by cknitt** [comment]
@jchavarri Thanks a lot for your contribution and for the helpful tip regarding GH actions, will definitely look into it!
