### ISSUE TITLE
Usage with bs-react-intl 2.x?

### ISSUE THREAD

**Issue by dfalling** [cknitt/bs-react-intl-extractor#61]
Hi again!  So I think I've properly upgraded my code to the changes in bs-react-intl 2.x, but ran into issues with extracting translations to json.  I'm using the [extraction script](https://github.com/reasonml-community/bs-react-intl/blob/master/examples/extractor/index.js) from bs-react-intl, and my locale file looks like this:

```ocaml
open ReactIntl;

[@intl.messages]
let appName = {id: "app.appName", defaultMessage: "Ido"};
let name = {id: "app.name", defaultMessage: "Name"};
...
```

I use _most_ of these translations with this component:
```ocaml
module DefinedMessage = {
  [@react.component]
  let make = (~message: ReactIntl.message, ~values=?, ~tagName=?) => {
    <ReactIntl.FormattedMessage
      id={message.id}
      defaultMessage={message.defaultMessage}
      ?values
      ?tagName
    />;
  };
};
```

When I try to export, I get an empty array.  Is there a step I'm missing or messed up to generate the proper output?

Thanks!

**Comment by cknitt** [comment]
Hi! You are missing a `;` after `[@intl.messages]` (it needs to be an attribute on the module, not on `appName`).

**Comment by dfalling** [comment]
Wow great eye- that was exactly it.  Thank you!
