### ISSUE TITLE
Any plans to support Rescript syntax?

### ISSUE THREAD

**Issue by dfalling** [cknitt/bs-react-intl-extractor#63]
Are you planning to add support for Rescript?  I haven't touched Reason's AST at all, but researching it I'm guessing this would need to use [rescript-lang/syntax](https://github.com/rescript-lang/syntax) instead of `esy-ocaml/reason` to do the parsing?

**Comment by cknitt** [comment]
Definitely! So far I have been holding off on that though as we will probably wait another month or two before migrating our first projects to ReScript syntax, and there are still a lot of changes/fixes ongoing in https://github.com/rescript-lang/syntax.

**Comment by dfalling** [comment]
Awesome, that's great to hear!
